apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: skaffold-mean-stack
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
  - image: gcr.io/PROJECT_ID/mean-stack-app
    context: third-party
    platforms: [linux/amd64]
manifests:
  rawYaml:
  - service.yaml
deploy:
  cloudrun: {}